### ISSUE TITLE
discum & telethon or pyrogram

### ISSUE THREAD

**Issue by erichegit** [Merubokkusu/Discord-S.C.U.M#111]
I am coding a Discord - Telegram bridge.

Sadly somehow DISCUM and other libraries which needs to be startet are not working for me inside one .py Project.
Do you have a suggestion, how to execute both libraries?

I tryed async (asyncio) and get

```
Unhandled exception in thread started by <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x7497b690>>
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/discum/gateway/gateway.py", line 288, in _response_loop
    func(resp)
  File "/home/pi/telegram/Discord_logging.py", line 62, in readmessages
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-2'.
channel: 528173488842997771 | username: NISS | Sell off holiday weekend starting in 40min
Unhandled exception in thread started by <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x7497b690>>
```
______________
arandomnewaccount:
since you're using async it might be easier to use [dolfies discord.py fork](https://github.com/dolfies/discord.py-self)

**Comment by erichegit** [comment]
thanks - helped me alot - with this library its working fine 👍
