### ISSUE TITLE
Can't get all members

### ISSUE THREAD

**Issue by i0Z3R0** [Merubokkusu/Discord-S.C.U.M#171]
I'm trying to get all the online members in a large server with over 1K members. I keep getting a keyerror. Here's my code: 
```import discum


bot = discum.Client(
    token='XXXXXXXXXXX.YYYYYYY.ZZZZZZ')

lguildid = '0'


@bot.gateway.command
def memberTest(resp):
    if bot.gateway.finishedMemberFetching(lguildid):
        lenmembersfetched = len(
            bot.gateway.session.guild(lguildid).members).large
        print(str(lenmembersfetched) + ' Members Fetched')
        bot.gateway.removeCommand(memberTest)
        bot.gateway.close()


async def getmembers(guild_id, channel_id):
    global lguildid
    lguildid = guild_id
    bot.gateway.fetchMembers(guild_id, channel_id)
    bot.gateway.run()
    f = open('members.txt', 'w')
    bot.gateway.session.guild(guild_id).large = True
    for memberID in bot.gateway.session.guild(guild_id).members:
        print(memberID)
        f.write(memberID + '\n')
    f.close()
    print('Finished')
```
I get an error message and the program pauses, then once in a while, repeats the error message: 
```...'09c9577c504f6467eee542d78760c45b', 'self_video': False, 'self_mute': True, 'self_deaf': False, 'request_to_speak_timestamp': None, 'mute': False, 'deaf': False, 'channel_id': '831041126952730644'}, {'user_id': '775114291539476481', 'suppress': False, 'session_id': 'b341d6e4afbf969bbe439484e5f56b0d', 'self_video': False, 'self_mute': False, 'self_deaf': False, 'request_to_speak_timestamp': None, 'mute': False, 'deaf': False, 'channel_id': '831041126952730644'}], 'id': '749525669259640862'}, {'voice_states': [], 'id': '881254293301264506'}]}}
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x1019dd5e0>>
Traceback (most recent call last):
  File "/Users/student/Library/Python/3.8/lib/python/site-packages/discum/gateway/gateway.py", line 237, in _response_loop
    function(resp, **params)
  File "/Users/student/Library/Python/3.8/lib/python/site-packages/discum/gateway/guild/combo.py", line 86, in fetchMembers
    if not self.gatewayobj.session.guild(guild_id).hasMembers or reset:
  File "/Users/student/Library/Python/3.8/lib/python/site-packages/discum/gateway/session.py", line 196, in hasMembers
    return len(Session.settings_ready['guilds'][self.guildID]['members']) == 0
KeyError: '885899178243403817'```
```
What should I do??
I don't seem to have an error in small servers. 
__________
arandomnewaccount:
lemme know what happens without the async, like in this example:
https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/examples/gettingGuildMembers.py

btw, if you'd like to use an asynchronous framework instead and fetch online members, https://github.com/dolfies/discord.py-self might be a bit easier (they have op14 member fetching support)

**Comment by Gowixx** [comment]
arandomnewaccount, for discord.py-self what's the function to fetch members? couldn't find it.

**Comment by i0Z3R0** [comment]
I realized that I used the wrong token that was banned so I changed it to my current one and it works. After adding a slightly higher wait time, it works 😃 Thanks for the help!
