### ISSUE TITLE
Discord Validate Phone Error

### ISSUE THREAD

**Issue by Vinyzu** [Merubokkusu/Discord-S.C.U.M#180]
I get this error when validating with phone:

```
 [+] (<discum.user.user.User->validatePhone) Post -> https://discord.com/api/v9/phone-verifications/verify
 [+] (<discum.user.user.User->validatePhone) {"phone": "MYNUM", "code": "844966"}
 [+] (<discum.user.user.User->validatePhone) Response <- b'\xef\xbf\xbd8\x00\x00dj]\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x1a\xef\xbf\xbdF\xef\xbf\xbd\x18:\x05\x00\xef\xbf\xbd\xef\xbf\xbdv,\xef\xbf\xbd\x0ex\x08to\xef\xbf\xbdTJ\x06\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xdb\x93\x15\xdc\x8b\x17\xcc\x8b\r\xd2\x9d\xef\xbf\xbd\xef\xbf\xbd\x17+\xef\xbf\xbd-\xef\xbf\xbd\xef\xbf\xbdJ\xef\xbf\xbd\xef\xbf\xbded\xef\xbf\xbd\xef\xbf\xbdt%\xef\xbf\xbd8\xef\xbf\xbdxrB\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd2\xef\xbf\xbd\x01\\\xef\xbf\xbdQ\xef\xbf\xbd\t\xef\xbf\xbd49$ng\xd6\xaa|>Nc\xef\xbf\xbd\xef\xbf\xbd+85{\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x06\xef\xbf\xbd\r\x03'
Exception in thread Thread-54:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\Tokify on Top\server2.py", line 236, in phone_verify
    helper.validate(str(response.json()['sms'][0]['code']))
  File "C:\Users\Administrator\Desktop\Tokify on Top\server2.py", line 183, in validate
    bot.validatePhone(number, code)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\discum.py", line 399, in validatePhone
    if result.status_code == 200 and "token" in result.json():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
_____________
arandomnewaccount:
im guessing you didn't install brotli?
You can check if you have it or not by trying to import brotli - let me know what it tells you.

**Comment by Vinyzu** [comment]
C:\Users\Administrator\Desktop\Tokify on Top>python server.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Tokify on Top\server.py", line 1, in <module>
    import brotli
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: Das angegebene Modul wurde nicht gefunden. (Couldnt find the given module)

C:\Users\Administrator\Desktop>pip install brotli
Requirement already satisfied: brotli in c:\users\administrator\appdata\roaming\python\python39\site-packages (1.0.9)

**Comment by Vinyzu** [comment]
fixxed it!

**Comment by FuckingToaster** [comment]
> fixxed it!

how exactly did you solved it? having this issue too
