### ISSUE TITLE
Errors trying to use proxies

### ISSUE THREAD

**Issue by 0ft3n** [Merubokkusu/Discord-S.C.U.M#188]
`bot = discum.Client(token=token, log=False, proxy_host=proxy[0], proxy_port=proxy[1])`

Error:

> Traceback (most recent call last):
>   File "C:\Users\dmitr\OneDrive\Рабочий стол\Development\python\DiscordAutomatorBradley\singlebot.py", line 28, in <module>
>     bot = discum.Client(token=token, log=False, proxy_host=proxy[0], proxy_port=proxy[1])
>   File "C:\Users\dmitr\OneDrive\Рабочий стол\Development\python\DiscordAutomatorBradley\venv\lib\site-packages\discum\discum.py", line 84, in __init__
>     self.__super_properties = imports.SuperProperties(self.s, buildnum=build_num, log=self.log).getSuperProperties(self.__user_agent, self.locale)
>   File "C:\Users\dmitr\OneDrive\Рабочий стол\Development\python\DiscordAutomatorBradley\venv\lib\site-packages\discum\start\superproperties.py", line 58, in getSuperProperties
>     reqbuildnum = self.requestBuildNumber()
>   File "C:\Users\dmitr\OneDrive\Рабочий стол\Development\python\DiscordAutomatorBradley\venv\lib\site-packages\discum\start\superproperties.py", line 22, in requestBuildNumber
>     discord_login_page_exploration = Wrapper.sendRequest(self.editedS, 'get', "https://discord.com/login", log=False).text #log set to False cause this takes up console space w/o giving meaningful info
> AttributeError: 'NoneType' object has no attribute 'text'
___________
arandomnewaccount:
it's erroring out on the build num req for some reason. Try setting a different user agent (just re-run the command or input a user_agent):
```python
bot = discum.Client(token=token, log=False, proxy_host=proxy[0], proxy_port=proxy[1])
#or
bot = discum.Client(token=token, log=False, proxy_host=proxy[0], proxy_port=proxy[1], user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20210615 Firefox/37.0')
```

**Comment by 0ft3n** [comment]
re-ran multiple times, and set this user agent, but still the same
_________
arandomnewaccount:
alr then, set the build number manually:
```python
bot = discum.Client(token=token, log=False, proxy_host=proxy[0], proxy_port=proxy[1], build_num=10080)
```

**Comment by 0ft3n** [comment]
`[gateway] < [Errno 11001] getaddrinfo failed
[gateway] websocket closed
[gateway] Connection Dropped. Retrying in 10 seconds.`

Is that a proxy problem at this point?

Edit: No matter how much different proxies i try, i always get this error
___________
arandomnewaccount:
hm. how did you install discum?

**Comment by 0ft3n** [comment]
Through pip

Edit: Tried to reinstall through git clone but still getting those errors

Edit edit: Maybe some specific requests version is required?
______________
arandomnewaccount:
no, because you're also getting errors for websocket_client. Are you running this in repl.it or pythonanywhere?

**Comment by 0ft3n** [comment]
In PyCharm on my PC

**Comment by 0ft3n** [comment]
Any thoughts ?
__________
arandomnewaccount: 
not sure - possibly an issue with your proxies. Try without proxies and if that still doesn't work, try out [discord.py-self](https://github.com/dolfies/discord.py-self).

**Comment by 0ft3n** [comment]
Thats what I've managed to reach when tried to set the bot up on VPS

[gateway] < [Errno -8] Servname not supported for ai_socktype
[gateway] websocket closed
[gateway] Connection Dropped. Retrying in 10 seconds.
[gateway] < [Errno -8] Servname not supported for ai_socktype
[gateway] websocket closed
[gateway] Connection Dropped. Retrying in 10 seconds.
_______
arandomnewaccount:
not sure, you could try running on repl.it (https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/examples/replit.py). See if it works there.

note, proxy inputs have changed. You can initialize your client using:
```python
bot = discum.Client(token='', proxy='username:password@255.255.255.255')
```
and change proxies if you want using:
```python
bot.switchProxy('user:password123@254.255.255.255')
```

edit: closing as inactive
