### ISSUE TITLE
i get this error message when i run the code 

### ISSUE THREAD

**Issue by LYZEN77** [Merubokkusu/Discord-S.C.U.M#19]
I am a kind of a beginner to all of this so don't blame me for a small mistake

`import discum
import time
        #bot = discum.Client(email=,password=) #note, this will not work if you have a MFA account
        #bot = discum.Client(email=,password=,proxy_host=,proxy_port=,user_agent=)
        #bot = discum.Client(email=,password=,token=) #works for all types of accounts
bot = discum.Client(token="") #works for all types of accounts, no profile editing however
        #bot = discum.Client(token=,proxy_host=,proxy_port=) #works for all types of accounts, no profile editing however
@bot.gateway.command
def myf(resp):
    guild_id = "765186126684094474"
    channel_id = '767056897106640927'
    bot.gateway.fetchMembers(guild_id, channel_id)
bot.gateway.run(auto_reconnect=True)

`

i see nothing wrong with it after i read the wiki, but what i get is:

Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001B303F263D0>>
Traceback (most recent call last):
  File "c:\users\user\pycharmprojects\pythonprojectnew\venv\src\discum\discum\gateway\gateway.py", line 232, in _response_loop
    func(resp)
  File "C:/Users/user/PycharmProjects/pythonProjectNEW/main.py", line 12, in myf
    bot.gateway.fetchMembers(guild_id, channel_id)
  File "c:\users\user\pycharmprojects\pythonprojectnew\venv\src\discum\discum\gateway\gateway.py", line 296, in fetchMembers
    "function": Guild(self).fetchMembers,
`NameError: name 'Guild' is not defined`

**Comment by LYZEN77** [comment]
i can change it myself rn, if that's the only problem, cuz i wanna do it faster

**Comment by LYZEN77** [comment]
gotcha but you should test everything before you post it on here to prevent this kinda situation

**Comment by LYZEN77** [comment]
dude i got some result here

**Comment by LYZEN77** [comment]
tho, how do you compare the `bot.gateway.fetchMembers()` to `client.get_all_members():` of the official api, what's the difference

**Comment by LYZEN77** [comment]
this didn't answer my question

**Comment by LYZEN77** [comment]
so

**Comment by LYZEN77** [comment]
i js change the Guild to GuildCombo and do what you said on the `bot.gateway.fetchMembers()` so it be equivalent to `client.get_all_members()`

**Comment by LYZEN77** [comment]
this is so fucking complicated, wdym change your fork of discum, also all i need is the client.get_all_members(): as simple as possible in discum not anything else and I would be thankful

**Comment by LYZEN77** [comment]
what you mean is that it's not even possible

**Comment by LYZEN77** [comment]
ik that the client.get_all_members(): is a coroutine so needs async, you will implement async then this into discum, how much time will it take you, estimated

**Comment by LYZEN77** [comment]
MONTHS! sounds so hopeless, i am searching for another way or closing the project then
