### ISSUE TITLE
Bot.GetMessage returning <Response [200]>

### ISSUE THREAD

**Issue by Loan-Shark** [Merubokkusu/Discord-S.C.U.M#197]
Ive been trying out DISCUM for a while and for half the machines I run it on Bot.GetMessage is returning a response object "<Response [200]>" not a string. Confused, I grabbed some of the sample code (posted below) and added one line as well as my token. As far as I can tell this issue only occurs when running discum in a windows 10 VM

```py
import discum     
bot = discum.Client(token='myTokenWasHere', log={"console":True, "file":False})
message = bot.getMessage("875200877131100200", "900237955619250187")
print(message)
@bot.gateway.command
def helloworld(resp):
    if resp.event.ready_supplemental: #ready_supplemental is sent after ready
        user = bot.gateway.session.user
        print("Logged in as {}#{}".format(user['username'], user['discriminator']))
    if resp.event.message:
        m = resp.parsed.auto()
        guildID = m['guild_id'] if 'guild_id' in m else None #because DMs are technically channels too
        channelID = m['channel_id']
        username = m['author']['username']
        discriminator = m['author']['discriminator']
        content = m['content']
        print("> guild {} channel {} | {}#{}: {}".format(guildID, channelID, username, discriminator, content))
bot.gateway.run(auto_reconnect=True)
```

The message that outputted was <Response [200]> but looking at the console logs I found what ive posted below. As far as I can tell its broken unicode as \xef\xbf\xbd occurs frequently and it corresponds to the � symbol. resp.parsed.auto() however still worked 100% as intended.

```
[+] (<discum.messages.messages.Messages->getMessage) Get -> https://discord.com/api/v9/channels/875200877131100200/messages?limit=1&around=900237955619250187
 [+] (<discum.messages.messages.Messages->getMessage) Response <- b'\xef\xbf\xbd\x1a\x02\x00\xef\xbf\xbdRU\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdG\x19V\x1e\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd1\x1e\xef\xbf\xbd\x1a\x08\xef\xbf\xbd\x16T\x00\x1d\t\xef\xbf\xbd}\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd]\xef\xbf\xbdL\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdt@\r\x16e\t\xef\xbf\xbd\xef\xbf\xbdY\x18iGN\xef\xbf\xbdNOqF\xef\xbf\xbd\x7f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbde\xef\xbf\xbd\x00\xe8\x89\x84\xef\xbf\xbd^k\xc3\xbd\xef\xbf\xbd\xc4\x9dE\x06\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x19\x03\x08b\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x02\x03 2\xef\xbf\xbd\xef\xbf\xbd\r\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd.\xef\xbf\xbd\xd5\x82\xef\xbf\xbdY\xef\xbf\xbd%\xef\xbf\xbdD\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x1a\x075\xef\xbf\xbd\xef\xbf\xbd.\xef\xbf\xbd%r\xef\xbf\xbd\x12i\xce\xb9\xef\xbf\xbd\xef\xbf\xbd)\xef\xbf\xbdi]\xef\xbf\xbd\\\xef\xbf\xbd)c\x00\xef\xbf\xbdTz\xef\xbf\xbd\x1fZ\x7f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xc8\x91s\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdi\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x072\xef\xbf\xbd\xef\xbf\xbd8\xef\xbf\xbd\xc9\x8aluF\x068\xef\xbf\xbd%\xef\xbf\xbd\xef\xbf\xbdTj\xef\xbf\xbdv\xef\xbf\xbdH\xca\x98H\xd9\xac\xef\xbf\xbd.\xef\xbf\xbd\xef\xbf\xbdt\xef\xbf\xbd\xef\xbf\xbd\x0b\x06 \x068\xef\xbf\xbd\xef\xbf\xbd\x01\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdg\x06\x18\xef\xbf\xbd\x0e\x0b\x06\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x01\xef\xbf\xbd\xd3\x90G\x0e\xef\xbf\xbd\xef\xbf\xbd\x087\xef\xbf\xbd%\xed\x8c\xa1\xef\xbf\xbd\x04\xef\xbf\xbd9\xef\xbf\xbd\xef\xbf\xbd*\x06\xef\xbf\xbd\xef\xbf\xbd\x16+\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdB\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd<\xef\xbf\xbd\x1dY\xef\xbf\xbdV@\xef\xbf\xbd\xef\xbf\xbd\x16~\xef\xbf\xbd\x15\xef\xbf\xbdc\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdW\xef\xbf\xbdPz\xef\xbf\xbdO\xef\xbf\xbd\xef\xbf\xbd%8\xef\xbf\xbd\xef\xbf\xbd7\xef\xbf\xbd\x1ba4i\xef\xbf\xbdB\xef\xbf\xbd\xef\xbf\xbd;\xef\xbf\xbdF\xdf\xb7u\xef\xbf\xbdc\\\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd[\xef\xbf\xbd\xef\xbf\xbdNy\xef\xbf\xbd\xef\xbf\xbd\x1b@\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdp\xd8\xb5u\xef\xbf\xbdl\xef\xbf\xbd7\xef\xbf\xbdP,tHs\xef\xbf\xbd\xef\xbf\xbd\x0b\xef\xbf\xbdW\x12\xef\xbf\xbd\x04\xef\xbf\xbd\xef\xbf\xbd^\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdw\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdm\xef\xbf\xbd\x0f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd3h3\xef\xbf\xbdK\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdCo\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x0f\x14|\xef\xbf\xbd\x1d\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdH\xef\xbf\xbd\x05\xef\xbf\xbd\xef\xbf\xbd?\x0cpL\x1d\xef\xbf\xbdB\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd7\xef\xbf\xbdc\x16\xef\xbf\xbdx.\xef\xbf\xbd\xef\xbf\xbd\x11\x03L\xef\xbf\xbd\xef\xbf\xbd7S\xef\xbf\xbd\xef\xbf\xbd\xd7\xb6\xef\xbf\xbd\xef\xbf\xbdT\x0f\x07\xef\xbf\xbd\x19c9\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x19\x03\xef\xbf\xbd \xef\xbf\xbd/9]\n\xef\xbf\xbdL*\x08\x15\xef\xbf\xbd\xef\xbf\xbd\n)\xef\xbf\xbd\xef\xbf\xbd(\xef\xbf\xbd\xef\xbf\xbdP\x1eK\xef\xbf\xbd\xe3\xbf\xb3\xef\xbf\xbd\xef\xbf\xbdz<2@$\x14H\xef\xbf\xbdtn5\xef\xbf\xbdie2\x19\xef\xbf\xbdC-\xda\x8a\x1fk\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdp4\xef\xbf\xbd\xef\xbf\xbdP\xef\xbf\xbds\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdt\x0c\x10\xef\xbf\xbd\xef\xbf\xbd6\x1f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd(\xef\xbf\xbd+/<\xef\xbf\xbd$\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdy\xef\xbf\xbd\xef\xbf\xbdj\xef\xbf\xbdf\xef\xbf\xbd\xef\xbf\xbd\'\xef\xbf\xbd\xcd\xa0\xef\xbf\xbd8Zg&\xef\xbf\xbdK\xc9\x8cq\x12\xef\xbf\xbd\xef\xbf\xbdb\xef\xbf\xbdC"P\xef\xbf\xbdY\xef\xbf\xbd\xef\xbf\xbdg\x06x\xef\xbf\xbd\xef\xbf\xbd]k\x07\x1f\xef\xbf\xbd\xef\xbf\xbd\x7f\x0c\x03'
```
______________
arandomnewaccount:
the reason you're getting these weird unicode characters is that you havent installed brotli correctly (https://github.com/google/brotli)

As for the <Response [200]>: as noted in the docs, most rest api wraps return a [requests.Response object](https://www.w3schools.com/python/ref_requests_response.asp) unless otherwise specified. So, you can get the data using:
```python
data = bot.getMessage('channel id', 'message id').json()
```

**Comment by Loan-Shark** [comment]
After force reinstalling brotli the same errors as above occur.
```
pip install --force-reinstall brotli
Collecting brotli
  Using cached Brotli-1.0.9-cp310-cp310-win_amd64.whl (383 kB)
Installing collected packages: brotli
  Attempting uninstall: brotli
    Found existing installation: Brotli 1.0.9
    Uninstalling Brotli-1.0.9:
      Successfully uninstalled Brotli-1.0.9
Successfully installed brotli-1.0.9
```

I was not adding the .json() because it would cause a crash and I was wanting to see if def helloWorld was working, the following code returns the error below.

```py
import discum
bot = discum.Client(token='myTokenWasHere', log={"console":True, "file":False})
message = bot.getMessage("875200877131100200", "900237955619250187").json()
print(message)
@bot.gateway.command
def helloworld(resp):
    if resp.event.ready_supplemental: #ready_supplemental is sent after ready
        user = bot.gateway.session.user
        print("Logged in as {}#{}".format(user['username'], user['discriminator']))
    if resp.event.message:
        m = resp.parsed.auto()
        guildID = m['guild_id'] if 'guild_id' in m else None #because DMs are technically channels too
        channelID = m['channel_id']
        username = m['author']['username']
        discriminator = m['author']['discriminator']
        content = m['content']
        print("> guild {} channel {} | {}#{}: {}".format(guildID, channelID, username, discriminator, content))
bot.gateway.run(auto_reconnect=True)
```

```
Traceback (most recent call last):
  File "c:\Users\Miles Packham\Desktop\DISCUMReport.py", line 3, in <module>
    message = bot.getMessage("875200877131100200", "900237955619250187").json()
  File "C:\Users\Miles Packham\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Miles Packham\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Miles Packham\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Miles Packham\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Also apologies for the lack of formatting before, hope things are more legible now.
____________
arandomnewaccount:
no worries.
hm try:
```python
message = bot.getMessage("875200877131100200", "900237955619250187").content
print(message)
```
and see what that prints

**Comment by Loan-Shark** [comment]
Used
```javascript
import discum
bot = discum.Client(token='my_token_was_here', log={"console":True, "file":False})
message = bot.getMessage("875200877131100200", "900237955619250187").content
print(message)
@bot.gateway.command
def helloworld(resp):
    if resp.event.ready_supplemental: #ready_supplemental is sent after ready
        user = bot.gateway.session.user
        print("Logged in as {}#{}".format(user['username'], user['discriminator']))
    if resp.event.message:
        m = resp.parsed.auto()
        guildID = m['guild_id'] if 'guild_id' in m else None #because DMs are technically channels too
        channelID = m['channel_id']
        username = m['author']['username']
        discriminator = m['author']['discriminator']
        content = m['content']
        print("> guild {} channel {} | {}#{}: {}".format(guildID, channelID, username, discriminator, content))
bot.gateway.run(auto_reconnect=True)
```
The content output was still unfortunately the same as before.
```
b'\x83\x1a\x02\x00\xe4RU\xa7\xf5\xefG\x19V\x1e\xa5\xa6\xb41\x1e\xd3\x1a\x08\x82\x16T\x00\x1d\t\xda}\xe2\x9a\xe4\xcf\xfa\x84]\xb8L\xab\xf2\x9d\xfft@\r\x16e\t\x92\xc2Y\x18iGN\xc3NOqF\xbc\x7f\xfa\xf5\x88e\xc4\x00\xe8\x89\x84\xb4^k\xc3\xbd\xd0\xc4\x9dE\x06\xd8\xef\xcf\x19\x03\x08b\x80\xc3\xdf\x02\x03 2\xc0\xba\r\xfa\x9f\x8a.\x9c\xd5\x82\xc8Y\xcb%\xe7D\x82\x88\xd0\x1a\x075\x80\xa5.\x9c%r\xc6\x12i\xce\xb9\xd2\xde)\xeai]\xf2\\\xe3)c\x00\xfcTz\xbf\x1fZ\x7f\x80\x9b\xd8\xe3\xc8\x91s\x99\x84\xf4i\x9a\x9c\xe2\xe3\xa8\x072\xc6\xf08\xa4\xc9\x8aluF\x068\x96%\xcd\xe5Tj\xecv\xcdH\xca\x98H\xd9\xac\xfe.\xe9\xdft\x8c\xd7\x0b\x06 \x068\xb4\x8e\x01\xfa\xbc\xe6g\x06\x18\xa6\x0e\x0b\x06\xf8\xf5\x87\x01\xe6\xd3\x90G\x0e\xfb\xe8\x087\xce%\xed\x8c\xa1\xf3\x04\x869\xf7\xd2*\x06\xc0\xab\x16+\x83\xfb\xb6B\xab\xf7\xac<\xc2\x1dY\xd3V@\x98\xf9\x16~\xb4\x15\xaec\xa9\xc0\xb9\x82W\xe1Pz\xbfO\xad\xd4%8\xab\xb97\xda\x1ba4i\xe2B\xbc\x81;\xa6F\xdf\xb7u\x86c\\\xba\xbe\xbc[\xf8\xd8Ny\xc5\xc6\x1b@\xa9\xb0\xd9p\xd8\xb5u\xdel\xa07\xb8P,tHs\x8e\xf7\x0b\xdfW\x12\xda\x04\x82\xc8^\xb5\xdb\xd2w\xf0\xff\xc5m\x9b\x0f\xba\xe2\xff3h3\xacK\x96\x98\xffCo\x9f\x81\xfc\x0f\x14|\xa9\x1d\xe3\xda\xd0H\xa5\x05\x99\xe7?\x0cpL\x1d\xe6B\x84\xe7\xff7\xb7c\x16\xecx.\xb5\xe6\x11\x03L\xf1\xb8\xe47S\xf6\xd1\xd7\xb6\x9a\xc5T\x0f\x07\xc6\x19c9\xe5\xa5\xc7\xd3\x19\x03\xa0 \xc1/9]\n\xfaL*\x08\x15\xb8\xda\n)\x88\xe8\x82(\x80\xafP\x1eK\xcf\xe3\xbf\xb3\x85\xeaz<2@$\x14H\xedtn5\xf4ie2\x19\xffC-\xda\x8a\x1fk\xe0\x9f\x8ap4\x8f\xe6P\xdas\xa3\xa5\xf3\x9et\x0c\x10\xe8\xb6\xdb6\x1f\xc0\x9f\xaa\xe3(\xc2+/<\xf7$\xa4\x94\xe4y\x86\xe4\xb8j\xb1f\xc7\xcb\'\x93\xcd\xa0\xe58Zg&\xe1\x85K\xc9\x8cq\x12\x83\x98b\x92C"P\xe7\xb4Y\xc9\xe7g\x06x\x9b\x87]k\x07\x1f\x88\xcf\x7f\x0c\x03'
```
_________
arandomnewaccount:
hm. weird. it's not decompressing for some reason. 
ill run some tests when i get the time

you could edit your bot's session headers:
```python
bot.s.headers.update({"Accept-Encoding": "gzip, deflate"})
```
