### ISSUE TITLE
Error from seemingly nothing

### ISSUE THREAD

**Issue by sudokit** [Merubokkusu/Discord-S.C.U.M#203]
```
Traceback (most recent call last):
  File "C:\Users\usr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discum\gateway\gateway.py", line 233, in _response_loop
    func(resp)
  File "C:\Users\usr\Files\AtThisPointIHave0IdeaWhatToNameTheseRandomProjects\fosh\Bot.py", line 23, in message
    m = resp.parsed.auto()
  File "C:\Users\usr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discum\gateway\parse.py", line 15, in auto
    if hasattr(self, self.response['t'].lower()):
AttributeError: 'NoneType' object has no attribute 'lower'
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001F8C5177FA0>>
```

and it seemingly errors for stuff like m['content'] and m['author']

```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000025B5199C490>>
Traceback (most recent call last):
  File "C:\Users\usr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discum\gateway\gateway.py", line 233, in _response_loop
    func(resp)
  File "C:\Users\usr\docs\AtThisPointIHave0IdeaWhatToNameTheseRandomProjects\fosh\Bot.py", line 25, in commands
    if m['content'].startswith('fs.'):
KeyError: 'content'
```
__________
arandomnewaccount:
id need to see more of your code to see what's going on

**Comment by sudokit** [comment]
So the
`AttributeError: 'NoneType' object has no attribute 'lower'
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001F8C5177FA0>>`
isnt anything in my code obv but the 
`if m['content'].startswith('fs.'):
KeyError: 'content'`
is this
```python
@client.gateway.command
def commands(resp):
    m = resp.parsed.auto()
    if m['content'].startswith('fs.'):
```
______________
arandomnewaccount:
alr well the 2nd error (the one with the m['content']) is because not every msg discord sends over the gateway is a message_create event. Some are voice_state_updates, some are guild_creates, etc. So, instead, you'll have to do this:
```python
@client.gateway.command
def commands(resp):
    if resp.event.message: #check if it's a message_create event
        m = resp.parsed.auto()
        if m['content'].startswith('fs.'):
            #do stuff
```
I'll fix first error today when I get the time.
actually, I realize, the first one isn't really an error since you shouldn't be doing ```m = resp.parsed.auto()``` without checking for the event type first. Ill think about it some more later.
