### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Sun870905** [Merubokkusu/Discord-S.C.U.M#277]
When I run the code below on my computer, I get a KeyError.
==========================================================
```
import discum
bot = discum.Client(token='myToken')

def close_after_fetching(resp, guild_id):
	if bot.gateway.finishedMemberFetching(guild_id):
		lenmembersfetched = len(bot.gateway.session.guild(guild_id).members) #this line is optional
		print(str(lenmembersfetched)+' members fetched') #this line is optional
		bot.gateway.removeCommand({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
		bot.gateway.close()

def get_members(guild_id, channel_id):
	bot.gateway.fetchMembers(guild_id, channel_id, keep="all", wait=1) #get all user attributes, wait 1 second between requests
	bot.gateway.command({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
	bot.gateway.run()
	bot.gateway.resetSession() #saves 10 seconds when gateway is run again
	return bot.gateway.session.guild(guild_id).members

members = get_members('914245880503238668', '914960330893955102')

for memberID in members:
	print(memberID)
```
KeyError is like this:
```
...
[gateway] > {'op': 1, 'd': 4}
[gateway] < {'t': None, 's': None, 'op': 11, 'd': None}
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000264F2E18C20>>
Traceback (most recent call last):
  File "C:\Users\Sun\AppData\Roaming\Python\Python38\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
    function(resp, **params)
  File "C:\Users\Sun\AppData\Roaming\Python\Python38\site-packages\discum\gateway\guild\combo.py", line 71, in fetchMembers
    self.gatewayobj.session.guild(guild_id).resetMembers() #reset
  File "C:\Users\Sun\AppData\Roaming\Python\Python38\site-packages\discum\gateway\session.py", line 246, in resetMembers
    Session.settings_ready['guilds'][self.guildID]['members'] = {}
KeyError: '914245880503238668'
```
The above error keeps repeating itself.
Can you tell me how to solve the above problem?
_________
arandomnewaccount:
means you're not in the guild

**Comment by Sun870905** [comment]
Okay, I got it.
Thank you!!! 👍
