### ISSUE TITLE
Could not retrieve discord build number.

### ISSUE THREAD

**Issue by Sun870905** [Merubokkusu/Discord-S.C.U.M#278]
When I run the code below on a computer, I get an error.
```
import discum
bot = discum.Client(token='myToken')

def close_after_fetching(resp, guild_id):
	if bot.gateway.finishedMemberFetching(guild_id):
		lenmembersfetched = len(bot.gateway.session.guild(guild_id).members) #this line is optional
		print(str(lenmembersfetched)+' members fetched') #this line is optional
		bot.gateway.removeCommand({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
		bot.gateway.close()

def get_members(guild_id, channel_id):
	bot.gateway.fetchMembers(guild_id, channel_id, keep="all", wait=1) #get all user attributes, wait 1 second between requests
	bot.gateway.command({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
	bot.gateway.run()
	bot.gateway.resetSession() #saves 10 seconds when gateway is run again
	return bot.gateway.session.guild(guild_id).members

members = get_members('914245880503238668', '914960330893955102')

for memberID in members:
	print(memberID)
```
The error is like this:
```
Retrieving Discord's build number...
Could not retrieve discord build number.
list index out of range
 [+] (<discum.start.login.Login->getXFingerprint) Get -> https://discord.com/api/v9/experiments
 [+] (<discum.start.login.Login->getXFingerprint) Response <- b'\x03\xef\xbf\xbd\x07\x00\xc4\x8a\xef
...
 xef\xbf\xbd1\\\xef\xbf\xbd\xef\xbf\xbdi$\x00w_\xef\xbf\xbd\xef\xbf\xbd\x00\x03'
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    bot = discum.Client(token='OTE5MzE3MDM0MzQ3NjgzOTEx.YbUDfQ.pCZxBhQpLBVNLtvQYAGpgQ-n-Aw')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\discum-1.4.0-py3.8.egg\discum\discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\discum-1.4.0-py3.8.egg\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\discum-1.4.0-py3.8.egg\discum\start\login.py", line 38, in getXFingerprint
    xfingerprint = reqxfinger.json().get('fingerprint')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line
337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line
355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Can you tell me how to solve this problem?
__________
arandomnewaccount:
you need to install brotli:
```
pip3.8 install brotli
```
or whatever pip cmd you use

if it still doesn't work, you could just skip build num and xfingerprint fetching since they aren't really needed for member fetching:
```py
bot = discum.Client(token='myToken', build_num=0, x_fingerprint='test')
```

**Comment by Sun870905** [comment]
Okay, I got it. 
Thank you! 👍
