### ISSUE TITLE
NameError: name 'bot' is not defined

### ISSUE THREAD

**Issue by 0xtrances** [Merubokkusu/Discord-S.C.U.M#281]
hello, i'm trying to make selfbots which type commands for a bot hourly and in return the bot gives a message with a button that i want my selfbots to click
```python
import os
from dotenv import load_dotenv
load_dotenv()

import time

import discum
from discum.utils.button import Buttoner

# Options
autoReconnectOption = False
consoleLog = False
fileLog = False

# Load tokens
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "tokens.txt")) as f:
	tokenlist = f.read().splitlines()

def hourLoop(resp, bot, channelID):
    if resp.event.ready_supplemental:
            user = bot.gateway.session.user
            print("Logged in as {}#{}".format(user['username'], user['discriminator']))
            while True:
                time.sleep(1)
                bot.sendMessage(channelID, 'hourly command loop')
                bot.gateway.command(clickButton)
                time.sleep(3605)

def clickButton(resp):
    if resp.event.message or resp.event.message_updated:
        m = resp.parsed.auto()
        if m['author']['id'] == 'example bot id':
            if len(m["components"]) > 0:
                embeds = m['embeds'][0]
                # If message has embed
                if len(embeds) > 0:
                    if "example target str" in embeds.get('title', ''):
                        buts = Buttoner(m['components'])
                        bot.click(
                            m["author"]["id"],
                            channelID=m["channel_id"],
                            guildID=m.get('guild_id'),
                            messageID=m["id"],
                            messageFlags=m["flags"],
                            data=buts.getButton(row=0, column=0)
                        )
                    else:
                        pass

clients = []
for i in range(len(tokenlist)):
	if i==0:
		clients.append(discum.Client(token=tokenlist[0], log={"console":consoleLog, "file":fileLog}))
		build_num = clients[0]._Client__super_properties['client_build_number']
	else:
		clients.append(discum.Client(token=tokenlist[i], build_num=build_num, log={"console":consoleLog, "file":fileLog}))
	clients[i].gateway.command(
        {
            "function": hourLoop, 
            "params": {"bot":clients[i], "channelID": os.getenv(f"CHANNEL{i}")}
        }
    )

import threading

def gatewayRunner(bot, result, index):
	bot.gateway.run(auto_reconnect=autoReconnectOption)
	result[index] = bot.gateway.session.user

num_clients = len(clients)
threads = [None] * num_clients
results = [None] * num_clients

for i in range(num_clients):
    threads[i] = threading.Thread(target=gatewayRunner, args=(clients[i] , results, i))
    threads[i].start()
    time.sleep(10)

for i in results: 
	print(i)
```
error:
```
bot.click(Traceback (most recent call last):

  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 292, in _response_loop
NameError: name 'bot' is not defined
    func(resp)
  File "d:\Desktop\multibots.py", line 39, in clickButton
    bot.click(
NameError: name 'bot' is not defined
```
so i'm not sure how to get the bot object into the 2nd function clickButton
_________________
arandomnewaccount:
clickButton needs a `bot` param just like hourLoop. You'll also need to change the `bot.gateway.command(clickButton)` line to input the `bot` param

**Comment by 0xtrances** [comment]
changed it to
```python
import os
from dotenv import load_dotenv
load_dotenv()

import time

import discum
from discum.utils.button import Buttoner

# Options
autoReconnectOption = False
consoleLog = False
fileLog = False

# Load tokens
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "tokens.txt")) as f:
	tokenlist = f.read().splitlines()

def hourLoop(resp, bot, channelID):
    if resp.event.ready_supplemental:
            user = bot.gateway.session.user
            print("Logged in as {}#{}".format(user['username'], user['discriminator']))
            while True:
                time.sleep(1)
                bot.sendMessage(channelID, 'hourly command loop')
                bot.gateway.command(clickButton(bot=bot))
                time.sleep(3605)

def clickButton(resp, bot):
    if resp.event.message or resp.event.message_updated:
        m = resp.parsed.auto()
        if m['author']['id'] == 'example bot id':
            if len(m["components"]) > 0:
                embeds = m['embeds'][0]
                # If message has embed
                if len(embeds) > 0:
                    if "example target str" in embeds.get('title', ''):
                        buts = Buttoner(m['components'])
                        bot.click(
                            m["author"]["id"],
                            channelID=m["channel_id"],
                            guildID=m.get('guild_id'),
                            messageID=m["id"],
                            messageFlags=m["flags"],
                            data=buts.getButton(row=0, column=0)
                        )
                    else:
                        pass

clients = []
for i in range(len(tokenlist)):
	if i==0:
		clients.append(discum.Client(token=tokenlist[0], log={"console":consoleLog, "file":fileLog}))
		build_num = clients[0]._Client__super_properties['client_build_number']
	else:
		clients.append(discum.Client(token=tokenlist[i], build_num=build_num, log={"console":consoleLog, "file":fileLog}))
	clients[i].gateway.command(
            {
                "function": hourLoop, 
                "params": {"bot":clients[i], "channelID": os.getenv(f"CHANNEL{i}")}
            }
        )
        clients[i].gateway.command(
            {
                "function": clickButton, 
                "params": {"bot":clients[i]}
            }
        )

import threading

def gatewayRunner(bot, result, index):
	bot.gateway.run(auto_reconnect=autoReconnectOption)
	result[index] = bot.gateway.session.user

num_clients = len(clients)
threads = [None] * num_clients
results = [None] * num_clients

for i in range(num_clients):
    threads[i] = threading.Thread(target=gatewayRunner, args=(clients[i] , results, i))
    threads[i].start()
    time.sleep(10)

for i in results: 
	print(i)
```
but i'm getting this error now
```
File "d:\Desktop\multibots.py", line 26, in hourLoop
    bot.gateway.command(clickButton(bot=bot))
TypeError: clickButton() missing 1 required positional argument: 'resp'
```
tried passing in resp in clickButton too but it didn't work because i think the resp from message with button and the resp i passed in is different
_________
arandomnewaccount:
nono you pass in bot to bot.gateway.command like this: 
```
bot.gateway.command(
    {
        "function": myfunction,
        "params": {"guild_id": "123123123", "channel_id": "321321321", "log": True},
    }
)
```
You can read more up on bot.gateway.command here: https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/General.md#gatewaycommand

**Comment by 0xtrances** [comment]
ah ok so before time.sleep(3605) i have
```python
bot.gateway.command(
                    {
                        "function": clickButton,
                        "params": {"bot": bot, "channelID": channelID},
                    }
                )
```
also added clickButton to the bots
```python
clients[i].gateway.command(
        {
            "function": clickButton, 
            "params": {"bot":clients[i], "channelID": os.getenv(f"CHANNEL{i}")}
        }
    )
```
now it's able to detect the message but can't click it for some reason
