### ISSUE TITLE
discum error on windows server 2012

### ISSUE THREAD

**Issue by Amirmkia** [Merubokkusu/Discord-S.C.U.M#305]
I writed app for discord and use from disum . this app run in my localhost but when I run app on windows server host 2012 I give this error : 
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Ahmadi\Discord forwarder\discordtotel.py", line 11, in <module>
    bot = json.loads(discum.Client(token="mfa.YccT2aQFFchs1o2UqqgnTfPVLzKmo3gNKBGNaKziyZCD49qV_4tVyJUnmk8pMZ6CQK9sJTLTwe0xd9i8t0gz", log=False))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discum-1.4.0-py3.9.egg\discum\discum.py", line 104, in init
    self.xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discum-1.4.0-py3.9.egg\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discum-1.4.0-py3.9.egg\discum\start\login.py", line 38, in getXFingerprint
    xfingerprint = reqxfinger.json().get('fingerprint')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
how I solve this ?

**Comment by qourman** [comment]
did you slove the problem?

**Comment by Amirmkia** [comment]
> did you slove the problem?

you need to install brotli

**Comment by Amirmkia** [comment]
I write email to  ***@***.*** and write this error and he or she
tell me that install brotli . I install brotli but again dont work :(((((((

**Comment by WarningDarbe** [comment]
> > did you slove the problem?
> 
> you need to install brotli

cant worked for me
