### ISSUE TITLE
KeyError Scraping members

### ISSUE THREAD

**Issue by IFeeLucky** [Merubokkusu/Discord-S.C.U.M#321]
Im having an issue scraping members 
`Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002F9653BC2A0>>
Traceback (most recent call last):
  File "C:\Users\sixlu\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
    function(resp, **params)
  File "C:\Users\sixlu\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\guild\combo.py", line 89, in fetchMembers
    ranges = self.getRanges(index, multiplier, self.gatewayobj.session.guild(guild_id).memberCount) if not endFetching else [[0],[0]]
  File "C:\Users\sixlu\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\session.py", line 376, in memberCount
    return Session.settings_ready['guilds'][self.guildID]['member_count']
KeyError: 929427257435488306`

yes, i checked and im the guild
it doesnt scrape, its an small guild and it starts looping
anyone know how to fix it or why is the error?
my code

`
def scrape(self, token, serverID, channelID):

    bot = discum.Client(token=token)

    def close_after_fetching(resp, guild_id):
        if bot.gateway.finishedMemberFetching(guild_id):
            lenmembersfetched = len(bot.gateway.session.guild(guild_id).members)
            print(str(lenmembersfetched)+' members fetched')
            bot.gateway.removeCommand({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
            bot.gateway.close()

    def get_members(guild_id, channel_id):
        bot.gateway.fetchMembers(guild_id, channel_id, keep="all", wait=1)
        bot.gateway.command({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
        bot.gateway.run()
        bot.gateway.resetSession() 
        return bot.gateway.session.guild(guild_id).members

    members = get_members(serverID, channelID) 
    save_ = []
    lest = members.keys()
    for key in lest:
        save_.append(key)

    with open('ids.txt', 'w') as file:
        file.write('\n'.join(save_))`

**Comment by xKluil** [comment]
+
