### ISSUE TITLE
Status not showing up

### ISSUE THREAD

**Issue by Gilgames000** [Merubokkusu/Discord-S.C.U.M#33]
Hi! I'm trying to make a self-bot that sets a custom status and then stays online forever. I tried this:

```python
import discum

bot = discum.Client(token="token")
bot.setStatus("my custom status")
bot.gateway.run(auto_reconnect=True)
```

The bot stays online, but the status doesn't show up when I check from another account. What am I doing wrong?
Cheers!

______________________________
arandomnewaccount:
oh I think see what's happening. 
What I think is going on here is the IDENTIFY message your client is sending out (when running ```bot.gateway.run()```  says to discord that your status is online (https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/discum/gateway/gateway.py#L64), which is then changing your status. I'm going to have to do a few more tests to confirm, and if that's indeed the case, then I'll be fixing it in an upcoming commit. 

If that's the case, then the custom status should show if you don't connect to the gateway...

edit: just tested it and the gateway connection does not affect the status so...
My other guess is that your other account is not getting updates for your current account's presence changes. See if the profile of your current account (viewed from your other account) shows the custom status (right-click on username -> click profile). If it does, then everything is working fine.

2nd edit:
I see now. Tried looking from my other account and couldn't see any evidence of status-changing on my main so...I've got 1 last idea and if that doesn't work idk (I'll have to try tmr since tonight I don't have much time). Thanks for bringing this issue up.

**Comment by Gilgames000** [comment]
Thanks for your time!

**Comment by Gilgames000** [comment]
Ah I see! Thank you for looking into this. Do you happen to know if there is also a gateway request for sending DMs or something like that? Because after I send 2 DMs with the HTTP request my accounts get locked (even though I use a 1 minute delay between messages and a phone-verified account).

**Comment by Gilgames000** [comment]
Thanks! One last thing. I noticed that if I do `bot.run(auto_reconnect=True)` after a while I get a `websocket closed` message and it shuts down. For now, I'm doing something along these lines:

```python
while True:
    bot.run(auto_reconnect=True)
```

Any better way to do it? (basically, I just want a bot that stays idle and displays a custom status)

**Comment by Gilgames000** [comment]
I don't know because I didn't time it last time, I'm gonna try and see if it closes again, maybe it was a random issue with the network.

**Comment by Gilgames000** [comment]
It's been 5 hours and it's still up, working perfectly. I don't know what happened the other day! Anyway I tried to to as you said for the DMs:
1- create DM channel
2- request it through the gateway
3- send message

but the account gets banned after 2 messages anyway lol
rip I guess :shrug:

**Comment by Gilgames000** [comment]
I didn't check it anymore since yesterday, but now I noticed that every few hours this happens

```Exception ignored in thread started by: <bound method User.setStatusHelper of <discum.user.user.User object at 0x7f481125ed00>>                                                   [10/1884]
Traceback (most recent call last):
  File "/home/gilgames/idle-bot/.venv/lib/python3.8/site-packages/discum/user/user.py", line 91, in setStatusHelper
    return Wrapper.sendRequest(self.s, 'patch', url, body, log=self.log)
  File "/home/gilgames/idle-bot/.venv/lib/python3.8/site-packages/discum/RESTapiwrap.py", line 58, in sendRequest
    response = getattr(prepReqSession, method)(url=url, **data) #where the actual request happens
  File "/home/gilgames/idle-bot/.venv/lib/python3.8/site-packages/requests/sessions.py", line 614, in patch
    return self.request('PATCH', url, data=data, **kwargs)
  File "/home/gilgames/idle-bot/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gilgames/idle-bot/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/gilgames/idle-bot/.venv/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='discord.com', port=443): Read timed out. (read timeout=None)
```

**Comment by Gilgames000** [comment]
But anyway it's still working so I'm gonna close the issue for now :shrug:
