### ISSUE TITLE
Can't get user info

### ISSUE THREAD

**Issue by ahihiyou20** [Merubokkusu/Discord-S.C.U.M#330]

**Comment by ahihiyou20** [comment]
So im trying to get user's username and id using:
```
bot.gateway.session.user['id']
```
_token and another information provied tho._

And i got this error while running:
```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x7d51fe1b90>>
Traceback (most recent call last):
  File "/data/data/files/usr/lib/python3.10/site-packages/discum/gateway/gateway.py", line 296, in _response_loop
    func(resp)
  File "/data/data/files/home/test.py", line 153, in on_ready
    user = bot.gateway.session.user
  File "/data/data/files/usr/lib/python3.10/site-packages/discum/gateway/session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'
```
I swear i connected to the gateway and somehow i got that error while running.

**Comment by Ninutes** [comment]
some issue, pls fix this error

**Comment by JuliaYuki** [comment]
Someone???
