### ISSUE TITLE
`bot.gateway.session.user` does not work

### ISSUE THREAD

**Issue by Errorcrafter** [Merubokkusu/Discord-S.C.U.M#334]
title. `bot.gateway.session.user` raises a KeyError. the code i am currently using:
```py
@bot.gateway.command
def startup(resp):
    if resp.event.ready_supplemental: #ready_supplemental is sent after ready
        user = bot.gateway.session.user
        bot.gateway.subscribeToGuildEvents(wait=0.25)
        print("Logged in as {}#{}".format(user['username'], user['discriminator']))
```

stacktrace:
```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000023880BBF9C0>>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 296, in _response_loop
    func(resp)
  File "c:\Users\User\Desktop\Python Stuff\PROGRAMS ACTUALLY MADE BY ME\Project\main.py", line 26, in startup
    user = bot.gateway.session.user
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\discum\gateway\session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'
```

@arandomnewaccount

**Comment by Errorcrafter** [comment]
i think its a problem with `set_settings_ready` not setting all the stuff before `ready_supplemental`, which is strange since this code worked before
______
arandomnewaccount:
try using a different token. Sometimes user accs dont receive the ready event (unknown reasons)

**Comment by MujurID** [comment]
i think in "#take care of channels" in /discum/gateway/start/parse.py , because if i disable i can get ready_data or ready_data["user"]

![image](https://user-images.githubusercontent.com/40834757/164170857-6b3aa553-15f4-44bc-826a-188564c19b67.png)

[https://github.com/vivinano/MudaeAutoBot/issues/137#issuecomment-1103557826](url)

**Comment by tranbtho98** [comment]
For my case, the channelTypes in discum/gateway/types.py got index out of bound. Adding more index in channelTypes seems to fix the problem on my end.
