### ISSUE TITLE
member scraping issue

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/Discord-S.C.U.M#344]
trying to fetch members from a server:

error:
```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002345D235210>>
Traceback (most recent call last):
  File "C:\Users\joooo\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
    function(resp, **params)
  File "C:\Users\joooo\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\guild\combo.py", line 89, in fetchMembers
    ranges = self.getRanges(index, multiplier, self.gatewayobj.session.guild(guild_id).memberCount) if not endFetching else [[0],[0]]
  File "C:\Users\joooo\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\session.py", line 376, in memberCount
    return Session.settings_ready['guilds'][self.guildID]['member_count']
KeyError: 'guilds'
```

**Comment by hahaleter** [comment]
same wtf is the cause?

**Comment by ghost** [comment]
idk

**Comment by hahaleter** [comment]
dis is mad annoying

**Comment by hahaleter** [comment]
when will discum finna fix this bru

**Comment by yelnady** [comment]
Same error again and again
