### ISSUE TITLE
getting members throws error

### ISSUE THREAD

**Issue by Daddy-Talpapa** [Merubokkusu/Discord-S.C.U.M#357]
my (skidded) code:

```py
import discum

bot = discum.Client(token = "{token}")

def close_after_fetching(resp, guild_id):
    if bot.gateway.finishedMemberFetching(guild_id):
        lenmembersfetched = len(bot.gateway.session.guild(guild_id).members)
        print(str(lenmembersfetched) + ' members fetched')
        bot.gateway.removeCommand({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
        bot.gateway.close()

def get_members(guild_id, channel_id):
    bot.gateway.fetchMembers(guild_id, channel_id, keep='all', wait=1)
    bot.gateway.command({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
    bot.gateway.run()
    bot.gateway.resetSession()
    return bot.gateway.session.guild(guild_id).members


members = get_members('{guild}', '{channel}')
memberslist = []

for memberID in members:
    memberslist.append(memberID)
    print(memberID)

f = open('users.txt', "a")
for element in memberslist:
    f.write(element + '\n')
f.close()`
```

error:
```
[gateway] < ping/pong timed out
Exception ignored in thread started by
: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001B30CF856D0>>
Traceback (most recent call last):
  File "C:\Users\OEM\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
    function(resp, **params)
  File "C:\Users\OEM\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\guild\combo.py", line 70, in fetchMembers
    if not self.gatewayobj.session.guild(guild_id).hasMembers and reset:
  File "C:\Users\OEM\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\session.py", line 233, in hasMembers
    if self.guildID not in Session.settings_ready['guilds']:
KeyError: 'guilds'```

**Comment by ghost** [comment]
same please explain how to fix that.
_______
arandomnewaccount:
for this specific situation, im seeing "[gateway] < ping/pong timed out" so Im guessing a network issue caused your client not to receive some packets.

**Comment by Daddy-Talpapa** [comment]
> same please explain how to fix that.
> 
> arandomnewaccount: for this specific situation, im seeing "[gateway] < ping/pong timed out" so Im guessing a network issue caused your client not to receive some packets.

i used a different token and it worked, no idea why
