### ISSUE TITLE
Slash Triggering error

### ISSUE THREAD

**Issue by discordgladiator2** [Merubokkusu/Discord-S.C.U.M#368]
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x7fcf6a295d50>>
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discum/gateway/gateway.py", line 300, in _response_loop
    function(resp, **params)
  File "bumper.py", line 21, in slashCommandTest
    mes=bot.triggerSlashCommand(str(botID), channelID=channelID, guildID=guildID, data=data, sessionID=bot.gateway.session_id) #and send it off
TypeError: triggerSlashCommand() got an unexpected keyword argument 'sessionID'
______________
arandomnewaccount:
you've got an old version of discum, uninstall and reinstall from the github (as shown on the readme)

**Comment by notruri** [comment]
remove `sessionID`
_________
arandomnewaccount:
discord requires session id for sending/triggering slash commands
