### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by norhu1130** [Merubokkusu/Discord-S.C.U.M#384]
Traceback (most recent call last):
  File "C:\Users\norhu1130\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "All_users_mention.py", line 216, in dm
    await dm_send(str(server),str(chan),inv,msg)
  File "All_users_mention.py", line 159, in dm_send
    members = get_members(guild_id=guild_id, channel_id=channel_id)
  File "All_users_mention.py", line 158, in get_members
    return bot.gateway.session.guild(guild_id).members
  File "C:\Users\norhu1130\AppData\Local\Programs\Python\Python38\lib\site-packages\discum\gateway\session.py", line 239, in members
    return Session.settings_ready['guilds'][self.guildID]['members']
KeyError: "<Message id=990302512957505561 channel=<TextChannel id=990281980883111952 name='general' position=0 nsfw=False news=False category_id=990281980883111950> type=<MessageType.default: 0> author=<Member id=853561869008502816 name='Unknownuser' discriminator='5927' bot=False nick=None guild=<Guild id=990281980417548421 name='TestServer' shard_id=None chunked=True member_count=2>> flags=<MessageFlags value=0>>"
______________
arandomnewaccount:
from the error, I see you're inputting `<Message id=990302512957505561 channel= type=<MessageType.default: 0> author=<Member id=853561869008502816 name='Unknownuser' discriminator='5927' bot=False nick=None guild=> flags=>` as the key whereas the guildID is a string discord snowflake (looks like "987391264545917011")

**Comment by Lofimit** [comment]
Please fix this, same issue here.

**Comment by Daddy-Talpapa** [comment]
bump
