### ISSUE TITLE
 The example https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/examples/gettingGuildMembers.py raises an error

### ISSUE THREAD

**Issue by tizxr** [Merubokkusu/Discord-S.C.U.M#398]
The error is like 
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001E33755DA60>>
Traceback (most recent call last):
  File "C:\Users\humum\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
    function(resp, **params)
  File "C:\Users\humum\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\guild\combo.py", line 89, in fetchMembers
    ranges = self.getRanges(index, multiplier, self.gatewayobj.session.guild(guild_id).memberCount) if not endFetching else [[0],[0]]
  File "C:\Users\humum\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\session.py", line 376, in memberCount
    return Session.settings_ready['guilds'][self.guildID]['member_count']
KeyError: 'guilds'
[gateway] < {'t': 'MESSAGE_CREATE', 's': 426, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2022-07-20T10:30:13.086000+00:00', 'referenced_message': None, 'pinned': False, 'mentions': [{'username': 'iqbotplayz', 'public_flags': 0, 'member': {'roles': [], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2022-07-20T10:30:12.847786+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'avatar': None}, 'id': '997615989829161122', 'discriminator': '4929', 'avatar_decoration': None, 'avatar': 'b3e7870aeb5223d78f226d8870186138'}], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['994336675419410465'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2022-07-06T20:18:57.380000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'avatar': None}, 'id': '999261945037344788', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '<@997615989829161122>, welcome to #2305!', 'components': [], 'channel_id': '999018772042096770', 'author': {'username': 'Apollo', 'public_flags': 65536, 'id': '824119071556763668', 'discriminator': '2300', 'bot': True, 'avatar_decoration': None, 'avatar': '6e2ce320c3347656af622ee1eca46ffc'}, 'attachments': [], 'guild_id': '986284871292952626'}}
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001E33755DA60>>
Traceback (most recent call last):
  File "C:\Users\humum\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
    function(resp, **params)
  File "C:\Users\humum\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\guild\combo.py", line 89, in fetchMembers
    ranges = self.getRanges(index, multiplier, self.gatewayobj.session.guild(guild_id).memberCount) if not endFetching else [[0],[0]]
  File "C:\Users\humum\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\session.py", line 376, in memberCount
    return Session.settings_ready['guilds'][self.guildID]['member_count']
KeyError: 'guilds'

can someone help lol

**Comment by jbaumgarten** [comment]
The project seems to be abandoned :(

**Comment by lucas-shelby** [comment]
Any updates on this issue?

**Comment by Daddy-Talpapa** [comment]
bump

**Comment by jjhesk** [comment]
bump
