### ISSUE TITLE
Error with token

### ISSUE THREAD

**Issue by jbaumgarten** [Merubokkusu/Discord-S.C.U.M#400]
Hi guys,

I have a problem with the login with "authorization" token.

`
import discum
bot = discum.Client(token='MY_TOKEN')`

On launch I have:

`(Web3miners) ➜  DC_scraper python test.py
Retrieving Discord's build number...
Could not retrieve discord build number.
invalid literal for int() with base 10: 'ull!=='
Traceback (most recent call last):
  File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/importmanager.py", line 10, in func
    return globals()[name](*args, **kwargs)
KeyError: 'Login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/home/Desktop/workspace/Python/perso/crypto/DC_scraper/test.py", line 12, in <module>
    bot = discum.Client(token='token')
  File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/importmanager.py", line 13, in func
    return globals()[name](*args, **kwargs)
  File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/start/login.py", line 26, in __init__
    self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
  File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding`

Did I miss something?

**Comment by ahihiyou20** [comment]
> Hi guys,
> 
> I have a problem with the login with "authorization" token.
> 
> ` import discum bot = discum.Client(token='MY_TOKEN')`
> 
> On launch I have:
> 
> `(Web3miners) ➜ DC_scraper python test.py Retrieving Discord's build number... Could not retrieve discord build number. invalid literal for int() with base 10: 'ull!==' Traceback (most recent call last): File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/importmanager.py", line 10, in func return globals()[name](*args, **kwargs) KeyError: 'Login'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/home/Desktop/workspace/Python/perso/crypto/DC_scraper/test.py", line 12, in bot = discum.Client(token='MTAwMTQ0MjU3NDk2MTIyMTcyMw.GoVRNn.wDCEhtIhZvHm3W-f8KzUZa0F57hUpbu8kTyXhU') File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/discum.py", line 104, in **init** self.__xfingerprint = self.getXFingerprint(generateIfNone=True) File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/discum.py", line 216, in getXFingerprint return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone) File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/importmanager.py", line 13, in func return globals()[name](*args, **kwargs) File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/site-packages/discum/start/login.py", line 26, in **init** self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8') File "/Users/home/opt/anaconda3/envs/Web3miners/lib/python3.10/base64.py", line 87, in b64decode return binascii.a2b_base64(s) binascii.Error: Incorrect padding`
> 
> Did I miss something?

Arandomnewaccount just update the login.py file yesterday to fix that issue, so maybe your discum is outdated. Reinstall it from Github should work
Here is the command:
```
python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum
```

**Comment by jbaumgarten** [comment]
Still the same problem. I'm looking for "authorization" in headers and taking the value as token but...

```
(Web3miners) [home@dev-julien python]$ python test.py 
Retrieving Discord's build number...
Discord is currently on build number 138254
Traceback (most recent call last):
  File "/home/home/.local/lib/python3.10/site-packages/discum/importmanager.py", line 10, in func
    return globals()[name](*args, **kwargs)
KeyError: 'Login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/home/python/test.py", line 19, in <module>
    bot = discum.Client(token="MY_TOKEN", log=True, user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/538.36")
  File "/home/home/.local/lib/python3.10/site-packages/discum/discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "/home/home/.local/lib/python3.10/site-packages/discum/discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "/home/home/.local/lib/python3.10/site-packages/discum/importmanager.py", line 13, in func
    return globals()[name](*args, **kwargs)
  File "/home/home/.local/lib/python3.10/site-packages/discum/start/login.py", line 26, in __init__
    self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
  File "/home/home/.conda/envs/Web3miners/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by jbaumgarten** [comment]
In file `/home/home/.local/lib/python3.10/site-packages/discum/start/login.py` if I change

```
                if '.' in token:
                        userId = token.split('.')[0] + '=' * (-len(token.split('.')[0]) % 4)
                        self.userID = base64.b64decode(userId).decode('utf-8')
#                       self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
```

it do the trick...
___________
arandomnewaccount:
will update pypi soon
