### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/Discord-S.C.U.M#401]
Retrieving Discord's build number...
Could not retrieve discord build number.
invalid literal for int() with base 10: 'ull!=='
Traceback (most recent call last):
  File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\importmanager.py", line 10, in func
    return globals()[name](*args, **kwargs)
KeyError: 'Login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\funwa\OneDrive\Рабочий стол\abc.py", line 3, in <module>
    bot = discum.Client(token=token)
  File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\importmanager.py", line 13, in func
    return globals()[name](*args, **kwargs)
  File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\start\login.py", line 26, in __init__
    self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
  File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by ghost** [comment]
> Retrieving Discord's build number... Could not retrieve discord build number. invalid literal for int() with base 10: 'ull!==' Traceback (most recent call last): File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\importmanager.py", line 10, in func return globals()[name](*args, **kwargs) KeyError: 'Login'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\funwa\OneDrive\Рабочий стол\abc.py", line 3, in bot = discum.Client(token=token) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\discum.py", line 104, in **init** self.__xfingerprint = self.getXFingerprint(generateIfNone=True) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\discum.py", line 216, in getXFingerprint return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\importmanager.py", line 13, in func return globals()[name](*args, **kwargs) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\start\login.py", line 26, in **init** self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8') File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\base64.py", line 87, in b64decode return binascii.a2b_base64(s) binascii.Error: Incorrect padding

I Have The Same Issue Even On Python3.10, Is Your Token A MTA Token? Because Mine Is

**Comment by ghost** [comment]
> Retrieving Discord's build number... Could not retrieve discord build number. invalid literal for int() with base 10: 'ull!==' Traceback (most recent call last): File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\importmanager.py", line 10, in func return globals()[name](*args, **kwargs) KeyError: 'Login'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\funwa\OneDrive\Рабочий стол\abc.py", line 3, in bot = discum.Client(token=token) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\discum.py", line 104, in **init** self.__xfingerprint = self.getXFingerprint(generateIfNone=True) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\discum.py", line 216, in getXFingerprint return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\importmanager.py", line 13, in func return globals()[name](*args, **kwargs) File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\start\login.py", line 26, in **init** self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8') File "C:\Users\funwa\AppData\Local\Programs\Python\Python37\lib\base64.py", line 87, in b64decode return binascii.a2b_base64(s) binascii.Error: Incorrect padding

I FOUND A FIX


edit login.py, then copy the if token startswith mfa. one, then replace the mfa. with MTA.

here is the modified login.py file: https://www.dropbox.com/s/2kedt3p73x8nrgo/login.py?dl=0

use it dude :)
__________
arandomnewaccount:
https://github.com/Merubokkusu/Discord-S.C.U.M/commit/1aad113ed2ff57e9d42b7ca781cd26eec3bf788f fixed the binascii error 10 days ago. Didn't know about the mta tokens ill fix that
