### ISSUE TITLE
Error: Incorrect Padding

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/Discord-S.C.U.M#403]
I Made An Account Disabler Recently, But Now I Get Errors When Im Trying To Login To The User Account:
   Traceback (most recent call last):
  File "C:\Users\jbsmi\Desktop\e\main.py", line 16, in disable_token
    user = discum.Client(token=TOKEN)
  File "C:\Users\jbsmi\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\jbsmi\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\jbsmi\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\importmanager.py", line 13, in func
    return globals()[name](*args, **kwargs)
  File "C:\Users\jbsmi\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\start\login.py", line 26, in __init__
    self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
  File "C:\Users\jbsmi\AppData\Local\Programs\Python\Python310\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by cwz6h** [comment]
I Fixed It. Check https://github.com/Merubokkusu/Discord-S.C.U.M/issues/404

**Comment by ghost** [comment]
I Fixed It. Check https://github.com/Merubokkusu/Discord-S.C.U.M/issues/401
_____________
arandomnewaccount:
will update pypi soon
