### ISSUE TITLE
TheGiverOfServers raises KeyError 'user'

### ISSUE THREAD

**Issue by TheWever** [Merubokkusu/Discord-S.C.U.M#424]
The example "TheGiverOfServers.py" raises an error:
```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x1077b13d0>>
Traceback (most recent call last):
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/discum/gateway/gateway.py", line 299, in _response_loop
    func(resp)
  File "/Users/.../Desktop/ATC - PTFS/Defuro/main.py", line 15, in recv_msg
    user = bot.gateway.session.user
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/discum/gateway/session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'
```

**Comment by NeutronBlast** [comment]
It seems like the ready_supplemental message isn't being sent causing the gateway connection to drop, did you try with a different token?

**Comment by TheWever** [comment]
Not yet. Can u try it out rq?
