### ISSUE TITLE
Awaiting for messages?

### ISSUE THREAD

**Issue by Jan3kk** [Merubokkusu/Discord-S.C.U.M#43]
Hi! I am currently creating a bot that drops and grabs cards from Karuta BOT. I have already managed to make it quite independent but in somewhat obscure way, it relies 100% on events. The thing that would help me **a lot** would be some way to wait for these messages, here's example:

_BOT sends command k!c, awaits for message from <@646937666251915264> on public channel, gathers message and adds reaction to it_

`bot.sendMessage(channel_ID, "k!c")
response = await bot.gateway.command
if response['content'] == "x":
    msg_ID = response['id']
    bot.addReaction(channel_ID, msg_ID, "✅")`

Is it possible? If so, could you give me a brief example/explaination on a way I can implement this? Thanks :)

**Comment by Jan3kk** [comment]
Also, I'm sorry but even after reading most of issues, I don't understand what's the token? I am using email+password to sign in and it works, although in the beginning of testing your library it was sometimes giving error:

`Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\discord-karuta-collector\send.py", line 99, in <module>
    bot2 = discum.Client(email=email2, password=pass2, log=False)
  File "C:\Users\xxx\Desktop\discord-karuta-collector\venv\lib\site-packages\discum\discum.py", line 73, in __init__
    self.__user_token, self.__xfingerprint = Login(self.s, self.discord, self.log).GetToken(email=email, password=password, secret=secret, code=code) #update token from "" to actual value
  File "C:\Users\xxx\Desktop\discord-karuta-collector\venv\lib\site-packages\discum\start\login.py", line 53, in GetToken
    self.__token = result['token']
KeyError: 'token'

Process finished with exit code 1`

Aren't tokens meant to be used in public API bots? 

btw:
I'm asking this in second comment because I started to upgrade my bots and I am still having this issue.
_________________________________
arandomnewaccount:
hey, for your first comment, you've almost got it. Here's what I'm thinking based on the info you provided:
```python
bot.sendMessage(channel_ID, "k!c")

@bot.gateway.command
def helloworld(resp, channel_ID='1293823982347'):
    if resp.event.message: #if MESSAGE_CREATE event
        m = resp.parsed.auto()
        if m['author']['id'] == '646937666251915264':
            msg_ID = m['id']
            bot.addReaction(channel_ID, msg_ID, "✅")

bot.gateway.run()
```
1st, the message is sent. Then the function, helloworld, is appended onto the gateway command list. All this function does is check if the author of new msgs == '646937666251915264' and then adds a reaction if that's the case. You could add more checking (channel id checks, guild id checks, whatever, if you want).


as for your second comment, email+password is ok. The problem is that when logging in on your default ip, sometimes discord will provide a captcha challenge. Therefore, logging in with email+password isn't as predictable as simply providing the token (which is why I'd recommend to just use your token).

> Aren't tokens meant to be used in public API bots?        

Both user accounts and bot accounts use tokens. When you successfully login to discord with your email+password, discord sends you your user token.

btw here's a nice screenshot from Dracovian/Discord-Scraper that shows where to find your user token: https://camo.githubusercontent.com/cdca341328496fee49e06f53b4805706587237785e5362c90f64ed4fa97c704c/68747470733a2f2f692e696d6775722e636f6d2f6f3953663043482e706e67

**Comment by Jan3kk** [comment]
Okay, thanks for the token tutorial, but with the first problem I think I didn't make it clear enough, because I am already using exact method you suggested in your response. Unfortunately, that way doesn't allow me to make long, chained conversations. I would like to know a way to block code executed in event-functions until I get a new event, something like this:

`@bot1.gateway.command
def react_(resp):
    if resp.raw['d']['content'] == "xxx":
        bot.sendMessage(channel_ID, "k!mt <@my_main_acc_id>")
        new_response = await react_() # <----- this code blocks execution of the rest of the code in a way that it waits for
                                  #        another message that would contain for example "yyy" in resp.raw['d']['content']
        if new_response['d']['content'] == "yyy":
             bot.addReaction(channel_ID, new_response['d']['id'], "✅")
        else:
             bot.addReaction(channel_ID, new_response['d']['id'], "🔒")`
I'm sorry for the formatting but I don't know why TABs disappear, here's formatted one on [pastebin](https://pastebin.com/ki14cYMd).

To make it even more clear for you, here's an real-life example:

me = my bot
a friend of mine = karuta bot

1. I send a letter to my friend using mail (paper, handwritten) with a question: "Can I borrow x from you?"
2. I wait for the reply # This would be await in the code
3. After x time, I get a letter with:
    - "yes":
       a) I send back a letter "thanks"
    - "no":
       a) I send back a letter "i hate you"
________________
arandomnewaccount:
ah ok, thanks for the clarification. Btw discum uses threading instead of async. Also, the reason why your code formatting is off is because you're using one \` instead of three. About blocking code, I suppose if you really wanted to you could either use a while loop or keep track of some sort of message_stream variable, but I'm not entirely sure that'd be necessary for this problem.

This is an edited version of your code in the pastebin that works:
```
@bot1.gateway.command 
def react_(resp): #this function will run after each response from discord
	if resp.event.message: #if MESSAGE_CREATE event
		m = resp.parsed.auto() #same thing as resp.parsed.message_create
		if m["content"] == "xxx":
			bot.sendMessage(channel_ID, "k!mt <@"+main_acc_id+">") 
		elif m["content"] == "yyy": 
			bot.addReaction(channel_ID, m["id"], "✅") 
		else:
			bot.addReaction(channel_ID, m["id"], "🔒")

bo1.gateway.run()
```
After doing a quick check up on katura's msg formatting, I rewrote some stuff. Renamed bot1 to bot and bot to friend (since bot1 seemed to be your main). Therefore, below, bot is your main account:
```
@bot.gateway.command
def react_(resp, channel_ID="channel_id_here", friend_id="friend_id_here"): #this function will run after each response from discord
	if resp.event.ready_supplemental: #on bot startup
		friend.sendMessage(channel_ID, "k!mt <@"+bot.gateway.session.user["id"]+">") #send initial msg, bot.gateway.session.user["id"] is the bot's user id
	if resp.event.message: #if MESSAGE_CREATE event
		m = resp.parsed.auto() #same thing as resp.parsed.message_create
		target_msg = "<@"+bot.gateway.session.user["id"]+">, would you like to trade with <@"+friend_id+">?"
		if m["author"]["id"]=="646937666251915264" and m["content"]==target_msg: #checks Karuta's id and target_msg match
			bot.addReaction(channel_ID, m["id"], "☑️")
	if resp.event.message_updated: #message update event
		edited_m = resp.parsed.auto()
		if "This trade session will expire in 10 minutes." in edited_m["embeds"][0]["description"]:
			friend.addReaction(channel_ID, edited_m["id"], "🔒")
			bot.addReaction(channel_ID, edited_m["id"], "🔒")
		elif "This trade has been locked." in edited_m["embeds"][0]["description"]:
			friend.addReaction(channel_ID, edited_m["id"], "✅")
			bot.addReaction(channel_ID, edited_m["id"], "✅")

bot.gateway.run()
```
Simply, what's happening above is after your bot connects to discord's gateway, your bot sends the k!mt command to the channel. Katura responds with a message (and we can check the contents of that msg). If everything looks good, a ☑️ reaction is made by your friend.  After that, Katura edits the embed to include `This trade session will expire in 10 minutes.`, so, we check for that and add the locked reaction with both accounts. After that, `This trade has been locked.` is edited into the embed and we check for that and react accordingly.

For some of these event-driven problems, if given the right conditionals, sequential data doesn't need to be considered. But, if you do need to check for something that occurred in an event in the past (like, a specific trade from katura that happened an hour ago, you can save them into instance variables and check them later that way.

edit: lemme know if that helps

No response so I'm closing this for now. Feel free to open another issue if you have other questions about this.
