### ISSUE TITLE
build number/getXFingerprint

### ISSUE THREAD

**Issue by pingu6** [Merubokkusu/Discord-S.C.U.M#434]
```
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\lord\MudaeAutoBot\pingu\farm kak\alt.1 Sukuna\MudaeAutoBot.py
Retrieving Discord's build number...
Could not retrieve discord build number.
list index out of range
[35m [+] (<discum.start.login.Login->getXFingerprint) Get -> https://discord.com/api/v9/experiments[m
[32m [+] (<discum.start.login.Login->getXFingerprint) Response <- b"c\x00`/\x00@\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdU{\xef\xbf\xbd\xef\xbf\xbd9#\xef\xbf\xbd\x16\xdd\x86\xef\xbf\xbd5A\x10\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd|c\x1b\xef\xbf\xbd\xef\xbf\xbd]D\x01M\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd8\xef\xbf\xbd\xef\xbf\xbdYv\x00sn\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd0\xef\xbf\xbd\x08\xef\xbf\xbd\x7f\xef\xbf\xbd\x7f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x7f~\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdx\x1d\x08\xc9\x99\xdd\xae\xce\x9aH\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdwg\xef\xbf\xbd\x0f\xef\xbf\xbd?\xef\xbf\xbd<\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x1f\xef\xbf\xbd\xdc\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd?\xef\xbf\xbd~\x1e\xef\xbf\xbd:\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x7f\xef\xbf\xbd\xef\xbf\xbd{8^\x17\x17N\xef\xbf\xbdU\x1c\xec\x85\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x17\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd(\xef\xbf\xbd(\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdW\xef\xbf\xbdu\xc4\xbdp\xef\xbf\xbd\xef\xbf\xbd\x05-A\x089{a/\xef\xbf\xbdu\xc4\xbdp\xef\xbf\xbd\xd7\x85y\xef\xbf\xbdXZp/\xef\xbf\xbdU\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbda\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd1\x11\xef\xbf\xbd\xef\xbf\xbd`\xef\xbf\xbdz&\x7f\xcc\x95\xef\xbf\xbde(r\x1f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x18\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd*\xef\xbf\xbd\xd2\xab\xd2\xb4\x11VI\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd}/\xef\xbf\xbdl((\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdF4\xef\xbf\xbd\xef\xbf\xbd\x00\xef\xbf\xbd\x05 2\xef\xbf\xbd\x1b\t\xef\xbf\xbd\xef\xbf\xbdT\x1b\x03\xef\xbf\xbd{xa$\xef\xbf\xbdte)\xef\xbf\xbdUe\xef\xbf\xbd\xef\xbf\xbd(]J\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd`h\xef\xbf\xbd^\xef\xbf\xbd8\x12\tU\x08r\xef\xbf\xbd\x04?\xef\xbf\xbd\xc2\x80\xef\xbf\xbd@\xef\xbf\xbd\x151\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x18\xef\xbf\xbd-\xef\xbf\xbdg\xef\xbf\xbd\xef\xbf\xbdN&\xef\xbf\xbdP\xef\xbf\xbd\xef\xbf\xbd9\xef\xbf\xbd\xef\xbf\xbdv\xdc\x84\xef\xbf\xbd\x06\nKH\xef\xbf\xbdX\xef\xbf\xbdCu\x1bk\xef\xbf\xbd\xef\xbf\xbdix\xef\xbf\xbd\x02\xef\xbf\xbd4et[\xef\xbf\xbdw\xef\xbf\xbdV\xef\xbf\xbdp\xef\xbf\xbd\xef\xbf\xbd&H^0\xef\xbf\xbd8S\xef\xbf\xbdQ]\x13\xef\xbf\xbd\xef\xbf\xbd*F\xef\xbf\xbds\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdm,\x1d\xef\xbf\xbd90%\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x05\xef\xbf\xbdg*d\x1e\xef\xbf\xbd\xc8\xbdJ\xef\xbf\xbd\xef\xbf\xbddJ{\x05!\xef\xbf\xbdyg\x0cE\xef\xbf\xbd\xef\xbf\xbdO &\xef\xbf\xbd\xef\xbf\xbd\x0b\xef\xbf\xbdL\x03\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdOt\xc6\xac\xef\xbf\xbd\x1c\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd%\xef\xbf\xbdR\xef\xbf\xbd\xef\xbf\xbdTg\xef\xbf\xbd|!\n7\xef\xbf\xbd\xef\xbf\xbdP\x13S#X\xef\xbf\xbd\xef\xbf\xbd\x06<\xef\xbf\xbd3h\xef\xbf\xbd\x08edMz\xc2\xbc\xef\xbf\xbd~R\xef\xbf\xbd\x06$9h6\xc6\x89\xef\xbf\xbd#\x18\xef\xbf\xbd\xef\xbf\xbd]t\x1e(\xef\xbf\xbdv\xef\xbf\xbd\xef\xbf\xbd\x07Dd\x05\xef\xbf\xbd\xef\xbf\xbd\\\xef\xbf\xbd\t 2\x14\xef\xbf\xbd\xef\xbf\xbdL\r\xef\xbf\xbd\xef\xbf\xbdC\xef\xbf\xbd\xd1\x91f!\x1b\x16\x16\xef\xbf\xbd;\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdB#T4\x03P \x00@\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x17\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd \xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdb\xdd\x86I\xef\xbf\xbd\xef\xbf\xbdig\xef\xbf\xbdY/\xef\xbf\xbdF\xef\xbf\xbd\xef\xbf\xbdA\xef\xbf\xbd\x079s\xef\xbf\xbd\xd5\x99\xef\xbf\xbd}\xef\xbf\xbd\xef\xbf\xbd\xcb\x93U<\xef\xbf\xbdV\xef\xbf\xbd\xef\xbf\xbd\x18\xef\xbf\xbd\xef\xbf\xbdZ\xef\xbf\xbd\x1fI\x04z\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x16\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x06\x0f\xef\xbf\xbd\nlUS\xef\xbf\xbdH!\xef\xbf\xbd\xef\xbf\xbd$\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdF\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdcQJ\xef\xbf\xbdj\xef\xbf\xbd\xef\xbf\xbd\xcd\x80\xe2\x97\xb3ZLEo\x05\x19\xef\xbf\xbdR,O\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x04G8\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd5\x1d\xef\xbf\xbd\xc6\xb7&\xef\xbf\xbd&\xef\xbf\xbdB\xef\xbf\xbd\xef\xbf\xbd'd@0Q\xef\xbf\xbdB\xef\xbf\xbd\xef\xbf\xbdj\xcb\x81i\xef\xbf\xbd\rM\x1c\xef\xbf\xbd\x11(\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd=\xef\xbf\xbd,\xef\xbf\xbd99\xef\xbf\xbd\x13c\xef\xbf\xbdE$\xef\xbf\xbdn:\xef\xbf\xbd\xef\xbf\xbdtrW\xef\xbf\xbd\xda\xb2\xef\xbf\xbdTg\xef\xbf\xbdQ9 f\xef\xbf\xbd\x11S\xef\xbf\xbd\xef\xbf\xbdr\x19\x12\xef\xbf\xbdcE!\xef\xbf\xbd\xef\xbf\xbd}\xef\xbf\xbd\xef\xbf\xbdyt\xd3\xacs\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdG\xef\xbf\xbd(\xef\xbf\xbd#,N\xef\xbf\xbd{\xef\xbf\xbd\xef\xbf\xbd\x1e\xef\xbf\xbd\xef\xbf\xbd\x10N7\rD\xef\xbf\xbd-\xef\xbf\xbd\n\xef\xbf\xbd22\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdjU\x1c`B1NS\xef\xbf\xbdBy|\xef\xbf\xbd&Z\xef\xbf\xbd8\x12-3\xef\xbf\xbdBqcdR\xcc\xa4u\x13\xef\xbf\xbd\xef\xbf\xbd[*\xef\xbf\xbdZKMcSN\xef\xbf\xbd9\xef\xbf\xbd\xef\xbf\xbdH\xef\xbf\xbd;\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd*\xef\xbf\xbd\xcc\xb5\xef\xbf\xbd\xef\xbf\xbd\x03"[m
Traceback (most recent call last):
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lord\MudaeAutoBot\pingu\farm kak\alt.1 Sukuna\MudaeAutoBot.py", line 19, in <module>
    bot = discum.Client(token=settings["token"],log={"console":True, "file":False})
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\start\login.py", line 38, in getXFingerprint
    xfingerprint = reqxfinger.json().get('fingerprint')
  File "C:\Users\lord\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by pingu6** [comment]
idk how or why but after i installed this https://github.com/abbodi1406/vcredist/releases/tag/v0.64.0 it works
