### ISSUE TITLE
gateway.session.guildIDs() does not work

### ISSUE THREAD

**Issue by cupzyy** [Merubokkusu/Discord-S.C.U.M#48]
```
print(discumbot.gateway.session.guildIDs())
discumbot.gateway.run()
discumbot.gateway.resetSession()
```
it gives the error:
```
Traceback (most recent call last):
  File "C:/Users/CUPZYY/Documents/Python Projects/Discord-Tag-Change-Bot/main.py", line 108, in <module>
    startFetch()
  File "C:/Users/CUPZYY/Documents/Python Projects/Discord-Tag-Change-Bot/main.py", line 103, in startFetch
    print(discumbot.gateway.session.guildIDs())
  File "C:\Users\CUPZYY\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\gateway\session.py", line 36, in guildIDs
    return [guildID for guildID in self.guilds if "removed" not in self.guilds[guildID]]
  File "C:\Users\CUPZYY\AppData\Local\Programs\Python\Python37\lib\site-packages\discum\gateway\session.py", line 28, in guilds
    return self.settings_ready['guilds']
KeyError: 'guilds'
```
____________
arandomnewaccount:
you have to connect to the gateway first in order to receive any gateway session data
so, like this:
```python
discumbot.gateway.run() #connect to the gateway, after a few seconds you can do ctrl-c
print(discumbot.gateway.session.guildIDs) #guildIDs is not callable so no ()
```

**Comment by cupzyy** [comment]
@arandomnewaccount 
that do not work as the code below `discumbot.gateway.run()` does not run
_________________
arandomnewaccount:
yea well what I gave was a minimal example (you can do ctrl-c to close gateway.run()).
Anyway, here's a full example:
```python
@discumbot.gateway.command
def closeAfterReceivingReadySupp(resp):
    if resp.event.ready_supplemental:
        discumbot.gateway.close()

discumbot.gateway.run() #will close automatically because of closeAfterReceivingReadySupp

print(discumbot.gateway.session.guildIDs)
```

However, I don't recommend closing the gateway just to receive the ready and ready supplemental data, so if you want to keep the gateway open, you can do this:
```python
@discumbot.gateway.command
def helloworld(resp):
    if resp.event.ready_supplemental:
        print(discumbot.gateway.session.guildIDs)

discumbot.gateway.run()
```

edit:
lemme know if this helped. If there's no response after a few more days I'll be closing this issue.

edit: closing this as answered.
