### ISSUE TITLE
AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by boguszk12** [Merubokkusu/Discord-S.C.U.M#64]
Hey I just wanted to ask what's up with that?
Happens when I try to get members.

`Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\websocket\_app.py", line 306, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Python39\lib\site-packages\websocket\_app.py", line 66, in read
    if not read_callback():
  File "C:\Python39\lib\site-packages\websocket\_app.py", line 274, in read
    return teardown(frame)
  File "C:\Python39\lib\site-packages\websocket\_app.py", line 231, in teardown
    if thread and thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'`
Thanks!
___________________
arandomnewaccount:
you just need to update your websocket-client installation 
(https://github.com/websocket-client/websocket-client/issues/641)

**Comment by boguszk12** [comment]
For future generations:
I edited the _app.py file in the directory.
________________
arandomnewaccount:
or you could just update your websocket-client installation...
