### ISSUE TITLE
[wanted help]Using proxy got AttributeError. how to solve this  issue?

### ISSUE THREAD

**Issue by mp1039447275** [Merubokkusu/Discord-S.C.U.M#84]
I checked proxy using curl, it's OK .
It worked on my windows computer. The error occur when I run the program on Linux server.
Anyone can help me?

Error Info:
 bot = discum.Client(token=token, proxy_host="**.**.96.131", proxy_port="8691",log=False)
  File "/root/.local/lib/python3.6/site-packages/discum/discum.py", line 86, in __init__
    self.__super_properties = SuperProperties(self.s, buildnum=build_num, log=self.log).getSuperProperties(self.__user_agent, None)
  File "/root/.local/lib/python3.6/site-packages/discum/start/superproperties.py", line 57, in getSuperProperties
    reqbuildnum = self.requestBuildNumber()
  File "/root/.local/lib/python3.6/site-packages/discum/start/superproperties.py", line 21, in requestBuildNumber
    discord_login_page_exploration = Wrapper.sendRequest(self.editedS, 'get', "https://discord.com/login", log=False).text #log set to False cause this takes up console space w/o giving meaningful info
  File "/root/.local/lib/python3.6/site-packages/discum/RESTapiwrap.py", line 102, in sendRequest
    text, color = Wrapper.logFormatter(function_name, response.text, part="response")
AttributeError: 'NoneType' object has no attribute 'text'
___________________________
arandomnewaccount:
run ```bot = discum.Client(token=token, proxy_host="**.**.96.131", proxy_port="8691",log=True)```
and paste the log info here. The error must be when getting the build number, but it's hard to pinpoint exactly where if log is set to False.

**Comment by mp1039447275** [comment]
I setted the log=True.

Randomly generated user agent: Mozilla/5.0 (Linux; Android 4.4.2; TM-MID790G Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36
Retrieving Discord's build number...
Traceback (most recent call last):
  File "test--.py", line 23, in <module>
    bot = discum.Client(token=token, proxy_host="", proxy_port="8691",log=True)
  File "/root/.local/lib/python3.6/site-packages/discum/discum.py", line 86, in __init__
    self.__super_properties = SuperProperties(self.s, buildnum=build_num, log=self.log).getSuperProperties(self.__user_agent, None)
  File "/root/.local/lib/python3.6/site-packages/discum/start/superproperties.py", line 57, in getSuperProperties
    reqbuildnum = self.requestBuildNumber()
  File "/root/.local/lib/python3.6/site-packages/discum/start/superproperties.py", line 21, in requestBuildNumber
    discord_login_page_exploration = Wrapper.sendRequest(self.editedS, 'get', "https://discord.com/login", log=False).text #log set to False cause this takes up console space w/o giving meaningful info
  File "/root/.local/lib/python3.6/site-packages/discum/RESTapiwrap.py", line 102, in sendRequest
    text, color = Wrapper.logFormatter(function_name, response.text, part="response")
AttributeError: 'NoneType' object has no attribute 'text'
____________________
arandomnewaccount:
hm ok...could you also do this test and paste the output:
```python
bot = discum.Client(token=token, proxy_host="**.**.96.131", proxy_port="8691", build_num=85732, log=True)
bot.getTrendingGifs()
```

**Comment by mp1039447275** [comment]
[root@woshishui test]# head  test.py 
import discum
import requests

token = "********************Jlt8g.klyM5h53x6sH8acuVp0vOMH0fj4"

bot = discum.Client(token=token, proxy_host="*.*.*.*", proxy_port="8691",log=True)
bot.getTrendingGifs()
bot.getDiscordStatus()
time.sleep(1)
#bot.getProfile()
[root@woshishui test]# python test.py 
Randomly generated user agent: SAMSUNG-GT-E3300V Opera/9.80 (J2ME/MIDP; Opera Mini/4.4.33943/58.167; U; th) Presto/2.12.423 Version/12.16
Retrieving Discord's build number...
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    bot = discum.Client(token=token, proxy_host="45.95.96.132", proxy_port="8691",log=True)
  File "/root/.local/lib/python2.7/site-packages/discum/discum.py", line 86, in __init__
    self.__super_properties = SuperProperties(self.s, buildnum=build_num, log=self.log).getSuperProperties(self.__user_agent, None)
  File "/root/.local/lib/python2.7/site-packages/discum/start/superproperties.py", line 57, in getSuperProperties
    reqbuildnum = self.requestBuildNumber()
  File "/root/.local/lib/python2.7/site-packages/discum/start/superproperties.py", line 21, in requestBuildNumber
    discord_login_page_exploration = Wrapper.sendRequest(self.editedS, 'get', "https://discord.com/login", log=False).text #log set to False cause this takes up console space w/o giving meaningful info
  File "/root/.local/lib/python2.7/site-packages/discum/RESTapiwrap.py", line 102, in sendRequest
    text, color = Wrapper.logFormatter(function_name, response.text, part="response")
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by mp1039447275** [comment]
I found the root cause.

in new urllib3 the main schema of proxy was changed...  (for urllib3=1.26.4).
An old
proxy={
    'http':'http://8.88.888.8:8888',
    'https':'https://8.88.888.8:8888'
    }
The new
proxy={
    'http':'8.88.888.8:8888',
    'https':'8.88.888.8:8888'
    }

so, I modified the code
```shell
vi +75 /root/.local/lib/python3.6/site-packages/discum/discum.py
```
```python
73                 if self.__proxy_host != None: #self.s.proxies defaults to {}
 74                         self.proxies = {
 75                         'http':  self.__proxy_host+':'+self.__proxy_port,
 76                         #'http': "http://" +  self.__proxy_host+':'+self.__proxy_port,
 77                         'https': self.__proxy_host+':'+self.__proxy_port
 78                         #'https': "https://" +  self.__proxy_host+':'+self.__proxy_port
 79                         }
```
It worked.

Thanks for your help.

**Comment by mp1039447275** [comment]
`73 if self.__proxy_host != None: #self.s.proxies defaults to {}
74 self.proxies = {
75 'http': self.__proxy_host+':'+self.__proxy_port,
76 #'http': "http://" + self.__proxy_host+':'+self.__proxy_port,
77 'https': self.__proxy_host+':'+self.__proxy_port
78 #'https': "https://" + self.__proxy_host+':'+self.__proxy_port
79 }`

1.
