### ISSUE TITLE
Overuse ram memory when run multi bots

### ISSUE THREAD

**Issue by SeinG0d** [Merubokkusu/Discord-S.C.U.M#86]
hi
i want to run multi bots but after some hours usage of ram grow up!
then my ram is full use and bots not working after this 
i use garbage collector (gc) and threads
but my issue is still alive
now i try use pypy for low usage of memory but i dont know about growing up memory usage realy
i wait for hourses and see ram usage and if my issue solved tell you more
________________________
arandomnewaccount:
the pypi version is outdated. The part of discum that can take up quite a lot of memory is the gateway session data.
Here're a few things you can do to lower ram usage (for each bot):
```python
bot.gateway.keepData = (,) #this tells discum to not keep "removed" data
```
```python
bot.gateway.session.saveMemory() #this removes some unused session data
```
Lemme know if that helps.

**Comment by SeinG0d** [comment]
bot.gateway.session.saveMemory() 
i use this line but my bots not online after this change
you can tell me where i can use this lines?
or give me a example code?
_________________
arandomnewaccount:
sure, here:
```python
import discum

with open("tokenlist.txt") as f:
	tokenlist = f.read().splitlines()

def test(resp, bot):
	if resp.event.ready_supplemental:
		bot.gateway.session.saveMemory()

clients = []
for i in range(len(tokenlist)):
	if i==0:
		clients.append(discum.Client(token=tokenlist[0]))
		build_num = clients[0]._Client__super_properties['client_build_number']
	else:
		clients.append(discum.Client(token=tokenlist[i], build_num=build_num))
	clients[i].gateway.command({"function":test, "params":{"bot":clients[i]}}) #add test to each bot
	clients[i].gateway.keepData = (,)

#now for the fun part
#we use threading to make it run fast. You can use multiprocessing or subprocess if you'd like to instead. This is just one implementation.
import threading

def gatewayRunner(bot):
	bot.gateway.run()

num_clients = len(clients)
threads = [None] * num_clients

for i in range(num_clients):
	threads[i] = threading.Thread(target=gatewayRunner, args=(clients[i],))
	threads[i].start()
```

Also, are you collecting any data with these bots or are you just connecting to the gateway?

**Comment by SeinG0d** [comment]
i just online them
you know ! I guessed this example tnx
but when i use :
if resp.event.ready_supplemental:
this if statement always get false
and not working
_____________
arandomnewaccount:
if you're never getting ready_supplemental events then your tokens are not working...
Two events are sent when a client starts: ready and ready_supplemental. Because these are sent at the start of the session, we can use them to run stuff right when our bot(s) connect to the gateway.

**Comment by SeinG0d** [comment]
my tokens working and my bots online but ready not get true
or im very tired and passed it 
i test this more :D
any way
thank your time
__________
arandomnewaccount:
if you want we can chat, might get this sorted out faster - you can email me at discordtehe@gmail.com

**Comment by SeinG0d** [comment]
oh we can chat but chats are not searchable :D
i use your example but my issue is still alive

**Comment by SeinG0d** [comment]
...

**Comment by SeinG0d** [comment]
some times i get exceptions like this
why?
this can stop threads?
why your client not clear data after get exceptions
or why not get param like saveMemory for clear not used data or use gc and not keep data and other :D
this can easyer for use low memory
and remove some intents from gateway can so helpful
```py
Exception ignored in thread started by: <bound method GatewayServer._heartbeat of <discum.gateway.gateway.GatewayServer object at 0x0000018CCA71C3D0>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 256, in _heartbeat
    self.send({"op": self.OPCODE.HEARTBEAT,"d": self.sequence})
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 262, in send
    self.ws.send(json.dumps(payload))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_app.py", line 182, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 283, in send
    return self.send_frame(frame)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 311, in send_frame
    l = self._send(data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 512, in _send
    return send(self.sock, data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 167, in send
    return _send()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
    return sock.send(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1175, in send
    return super().send(data, flags)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

**Comment by SeinG0d** [comment]
or get this exception sometimes :D 
if you watch my code i write function reconn for reconnect bot when threads not alive and get exceptions
but bots if relogin  
this happen shutdown another bots 
```py
OSError: [WinError 10038] An operation was attempted on something that is not a socket
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    return super().send(data, flags)
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1175, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    raise WebSocketConnectionClosedException("socket is already closed.")
    return send(self.sock, data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 145, in send
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 145, in send
    l = self._send(data)
    l = self._send(data)
    return _send()
    return send(self.sock, data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 167, in send
    return self._sslobj.write(data)
    return self.send_frame(frame)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 311, in send_frame
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 145, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 145, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 512, in _send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    return send(self.sock, data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 145, in send
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    l = self._send(data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 512, in _send
    raise WebSocketConnectionClosedException("socket is already closed.")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 512, in _send
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
    l = self._send(data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_core.py", line 512, in _send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    return sock.send(data)
    return send(self.sock, data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 167, in send
    return send(self.sock, data)
    return super().send(data, flags)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
    raise WebSocketConnectionClosedException("socket is already closed.")
    return send(self.sock, data)
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    return sock.send(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send
    return super().send(data, flags)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 145, in send
    return send(self.sock, data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
    return send(self.sock, data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 167, in send
    return sock.send(data)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1175, in send
    return super().send(data, flags)
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 167, in send
    return _send()
    return sock.send(data)
    return self._sslobj.write(data)
    return _send()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send
    return sock.send(data)
    return _send()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    return self._sslobj.write(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 145, in send
    return _send()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
    return sock.send(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1175, in send
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
    return sock.send(data)
    return super().send(data, flags)
    return self._sslobj.write(data)
    return sock.send(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1175, in send
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1173, in send
OSError: [WinError 10038] An operation was attempted on something that is not a socket
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
OSError: [WinError 10038] An operation was attempted on something that is not a socket
    return self._sslobj.write(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
    return super().send(data, flags)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
    return self._sslobj.write(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\websocket\_socket.py", line 149, in _send
    return self._sslobj.write(data)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
    return sock.send(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1175, in send
    return super().send(data, flags)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
Exception ignored in thread started by: <bound method GatewayServer._heartbeat of <discum.gateway.gateway.GatewayServer object at 0x000001996F449AF0>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 253, in _heartbeat
Exception ignored in thread started by: <bound method GatewayServer._heartbeat of <discum.gateway.gateway.GatewayServer object at 0x000001996F5D9820>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 253, in _heartbeat
Exception ignored in thread started by: <bound method GatewayServer._heartbeat of <discum.gateway.gateway.GatewayServer object at 0x000001996FE5CA30>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 253, in _heartbeat
Exception ignored in thread started by: <bound method GatewayServer._heartbeat of <discum.gateway.gateway.GatewayServer object at 0x000001996F692430>>
    time.sleep(self.interval)
Traceback (most recent call last):
Exception ignored in thread started by: <bound method GatewayServer._heartbeat of <discum.gateway.gateway.GatewayServer object at 0x000001996F514DF0>>
    time.sleep(self.interval)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 253, in _heartbeat
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 253, in _heartbeat
    time.sleep(self.interval)
TypeError: an integer is required (got type NoneType)
TypeError: an integer is required (got type NoneType)
    time.sleep(self.interval)
TypeError: an integer is required (got type NoneType)
    time.sleep(self.interval)
TypeError: an integer is required (got type NoneType)
TypeError: an integer is required (got type NoneType)
```
______________________
arandomnewaccount:
uh, I think your code could benefit from a little simplification and organization imo. Here, email me at discordtehe@gmail.com and Ill send you my discord there.

**Comment by SeinG0d** [comment]
i send email to you
_________
arandomnewaccount:
fixing this in https://github.com/Merubokkusu/Discord-S.C.U.M/tree/development using __slots__ + fixed the self.interval error
some things are still broken in development branch so...i'll have to do some more debugging

edit: things were fixed when dev branch got merged.

closing as it's been a while. might reopen issue in the future
